name: Docker Image CI

on:
  push:
    branches: ["main"]
    paths:
      - "wisecow.sh"   # Runs only if this file changes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t pranavparihar/wisecow:latest .

      - name: Push Docker Image
        run: docker push pranavparihar/wisecow:latest
